# Generated by Django 5.1.3 on 2024-12-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiFetchLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_category', models.BooleanField(default=False)),
                ('category_num', models.IntegerField(default=0)),
                ('modify_category', models.DateTimeField(null=True)),
                ('is_areacode', models.BooleanField(default=False)),
                ('areacode_num', models.IntegerField(default=0)),
                ('modify_areacode', models.DateTimeField(null=True)),
                ('is_sigungucode', models.BooleanField(default=False)),
                ('sigungu_num', models.IntegerField(default=0)),
                ('modify_sigungucode', models.DateTimeField(null=True)),
                ('is_place', models.BooleanField(default=False)),
                ('place_num', models.IntegerField(default=0)),
                ('modify_place', models.DateTimeField(null=True)),
                ('is_event', models.BooleanField(default=False)),
                ('event_num', models.IntegerField(default=0)),
                ('modify_event', models.DateTimeField(null=True)),
            ],
        ),
    ]
