# Generated by Django 5.1.3 on 2024-12-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCode',
            fields=[
                ('area_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('region_code', models.CharField(max_length=2)),
                ('region_name', models.CharField(max_length=2)),
            ],
        ),
    ]
