# Generated by Django 5.1.3 on 2024-12-05 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areacode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacode',
            name='region_code',
        ),
        migrations.RemoveField(
            model_name='areacode',
            name='region_name',
        ),
        migrations.AddField(
            model_name='areacode',
            name='image_url',
            field=models.CharField(default='/static/404_error.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='areacode',
            name='area_code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SigunguCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sigungu_code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=10)),
                ('area_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areacode.areacode')),
            ],
        ),
    ]
