# Generated by Django 5.1.3 on 2024-12-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areacode', '0004_alter_areacode_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sigungucode',
            name='sigungu_code',
            field=models.IntegerField(),
        ),
    ]
