# Generated by Django 5.1.3 on 2024-12-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                (
                    "verification_code",
                    models.CharField(max_length=6, verbose_name="인증 코드"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="만료일")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="인증 여부"),
                ),
            ],
            options={
                "verbose_name": "이메일 인증",
                "verbose_name_plural": "이메일 인증",
                "db_table": "email_verification",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False, verbose_name="이메일 인증 여부"),
        ),
    ]
