# Generated by Django 5.1.3 on 2024-12-05 01:22
# 이 파일은 이메일 인증 기능을 위한 데이터베이스 구조를 생성합니다.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),  # 이전 마이그레이션 파일에 대한 의존성
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",  # 이메일 인증 정보를 저장하는 테이블
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                # 사용자가 입력한 이메일 주소
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                (
                    # 시스템이 생성한 6자리 인증 코드
                    "verification_code",
                    models.CharField(max_length=6, verbose_name="인증 코드"),
                ),
                (
                    # 인증 코드가 생성된 시간
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                # 인증 코드의 유효 기간 (30분)
                ("expires_at", models.DateTimeField(verbose_name="만료일")),
                (
                    # 이메일이 성공적으로 인증되었는지 여부
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="인증 여부"),
                ),
            ],
            options={
                "verbose_name": "이메일 인증",
                "verbose_name_plural": "이메일 인증",
                "db_table": "email_verification",  # 실제 데이터베이스 테이블 이름
            },
        ),
        migrations.AddField(
            model_name="user",  # 기존 사용자 모델에 이메일 인증 상태 필드 추가
            name="is_email_verified",
            field=models.BooleanField(default=False, verbose_name="이메일 인증 여부"),
        ),
    ]
