# Generated by Django 5.1.3 on 2025-01-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="활성여부"),
        ),
    ]
