# Generated by Django 5.1.3 on 2025-01-10 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_is_active"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailVerification",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_email_verified",
        ),
    ]
