# Generated by Django 5.1.3 on 2024-12-02 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areacode', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('map_x', models.CharField(max_length=20)),
                ('map_y', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=13)),
                ('image', models.CharField(max_length=100)),
                ('thumb_img', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='category.category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='areacode.areacode')),
            ],
        ),
    ]
