# Generated by Django 5.1.3 on 2024-12-04 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areacode', '0001_initial'),
        ('category', '0001_initial'),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='area_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='areacode.areacode'),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='category.category'),
        ),
    ]
