# Generated by Django 5.1.3 on 2024-12-06 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areacode', '0005_alter_sigungucode_sigungu_code'),
        ('category', '0001_initial'),
        ('place', '0004_alter_place_homepage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AlterField(
            model_name='place',
            name='sigungu_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areacode.sigungucode'),
        ),
    ]
