# Generated by Django 5.1.3 on 2024-12-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_alter_place_category_alter_place_sigungu_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
