# Generated by Django 5.1.3 on 2024-12-16 02:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='place',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('place', 'user')},
        ),
    ]
