# Generated by Django 5.1.3 on 2024-12-16 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_rename_post_like_place_alter_like_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroller_rental', models.BooleanField(default=False, verbose_name='유모차 대여')),
                ('credit_card', models.BooleanField(default=False, verbose_name='신용카드 사용 가능')),
                ('pet_friendly', models.BooleanField(default=False, verbose_name='애완동물 동반 가능')),
                ('parking', models.BooleanField(default=False, verbose_name='주차 시설')),
                ('restroom', models.BooleanField(default=False, verbose_name='화장실')),
                ('elevator', models.BooleanField(default=False, verbose_name='엘리베이터')),
                ('wheelchair_path', models.BooleanField(default=False, verbose_name='휠체어 통로')),
                ('wheelchair_rental', models.BooleanField(default=False, verbose_name='휠체어 대여')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
