# Generated by Django 5.1.3 on 2024-12-16 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0011_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='views',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='viewed_places', to=settings.AUTH_USER_MODEL),
        ),
    ]
