# Generated by Django 5.1.3 on 2024-12-17 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0011_comment'),
        ('place', '0012_views_users'),
    ]

    operations = [
    ]
