# Generated by Django 5.1.3 on 2024-12-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='배너 제목', max_length=100)),
                ('image', models.CharField(help_text='배너 이미지 파일을 업로드하세요.', max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='활성 상태 여부')),
            ],
        ),
    ]
