# Generated by Django 5.1.3 on 2024-12-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touradmin', '0002_rename_image_bannerimage_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerimage',
            name='id',
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='title',
            field=models.CharField(help_text='배너 제목', max_length=100, primary_key=True, serialize=False),
        ),
    ]
